version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/python-proj

hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root
